debug: true

server:
  port: 11053
  servlet:
    session:
      cookie:
        secure: true
        same-site: "lax"

spring:  profiles:    active: local

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    jdbc-type-for-null: "NULL"

ustra:  core:    process-info:      default-system-code: POS
    properties:      encryption:
        enabled: true        key: 1kgn4879910xx6p8pobsr60eix5penwe
  data:
    datasource:
      default-datasource-name: rds1      datasources:        rds1:
          url: jdbc:log4jdbc:oracle:thin:@framework-oracle.c0uiyan5ae24.ap-northeast-2.rds.amazonaws.com:1521/GSITMSI
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: ENC(PYI1xRxj0lDoZs2VI7z8ew==)
          password: ENC(4YlOpi2kJc9fbyYLg+o9uhBi6gcoi1UG)
          properties:            max-lifetime: 300
  mvc:
    res:      add-res-cookie: false
    view:
      api-prefix: api
      client-crypto-key: eGZ1MDE2eHc2OGc1dWh3OQ==
      type: static_thyemeleaf
    rest:
      exclude-wrapping-url-patterns: /v2/api-docs,/swagger-resources/**,/swagger-ui.html,/webjars/**
      default-error-status-code: 500
    wrapper:
      exclude-request-url-patterns: /v2/api-docs
      exclude-response-url-patterns: /v2/api-docs
      
smsb: 
  pos: 
    sample-prop: posSampleProp
---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: stg
      
      
---
spring.config.activate.on-profile: prd
